name: hopperfinder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20
  - scipy>=1.7
  - matplotlib>=3.5
  - pip:
      - audian
      - thunderhopper
      - thunderlab
      - librosa
      - opencv-python
